### ISSUE TITLE
Setup the url and pages

### ISSUE THREAD

**Issue by tai271828** [pycontw/pycontw-blog#2]
Several things needed to be done come to my mind:

- [x] @Lee-W  create the first page. make sure github page works and tell me the url
- [x] @tai271828 associate the CNAME and url

**Comment by Lee-W** [comment]
I have a typo on the github action. 😞 That's why we don't have page now.

**Comment by tai271828** [comment]
We have the page now https://pycontw.github.io/pycontw-blog/

**Comment by tai271828** [comment]
http://conf.python.tw/ is ready.

Next step: enable https

**Comment by Lee-W** [comment]
we now have [conf.python.tw](http://conf.python.tw/) with https 🎉

**Comment by tai271828** [comment]
> we now have [conf.python.tw](http://conf.python.tw/) with https tada
!!! I thought I made incorrect configuration last night... I don't know why it works spontaneously. @Lee-W did you do anything on the configuration? Or it is just taking time to propagate my DNS settings last night. Orz

**Comment by tai271828** [comment]
Since the url works anyway, let move the remaining actions to https://github.com/pycontw/pycontw-blog/issues/10 . Closing this issue.

**Comment by tai271828** [comment]
> Looks like you forget to set the `conf.python.tw` on the github side laughing Never mind. It's now working tadatadatada

hmmm interesting. I did setup the field at the very beginning but github complains for checking DNS unsuccessfully, and then I removed it IIRC....

**Comment by Lee-W** [comment]
AFAIK, we need to wait some time after we set it up on gandi. It's one of the possible reason I can think of 🤔
