### ISSUE TITLE
[Feat Request] Add like👍 feature on article

### ISSUE THREAD

**Issue by winniepopu** [pycontw/pycontw-blog#35]
as title

I think we can add like👍 button on article, and maybe more emojis?

**Comment by Lee-W** [comment]
https://applause-button.com/

@winniepopu it might be something similar to what we want. do you want to take a look?

**Comment by winniepopu** [comment]
Sure, I would take a look. Thanks!

**Comment by Lee-W** [comment]
I think this has been added by @winniepopu . Close this one
