### ISSUE TITLE
[Feat Request] Add a message to indicate to login to Github to leave a comment

### ISSUE THREAD

**Issue by CYFish** [pycontw/pycontw-blog#36]
The user is required to login to Github to leave a comment, but there is no any indication.
It might be clear to add a description `Please login to Github to comment.` in the comment block.

**Comment by iknowright** [comment]
@CYFish ![image](https://github.com/pycontw/pycontw-blog/assets/25934612/df32824a-5a57-469c-a93e-cd7c72733c5a)
It has an indication by default. I can reproduce this by viewing the blog using incognito mode.

**Comment by CYFish** [comment]
Thank you for your assistance. It seems that the UI has been updated, and I cannot reproduce the initial issue.

The current indication is great, and I don't have any other concerns 😄 💯
